import { describe, expect, test } from "vitest";
import { day8part1, day8part2 } from "./day8";
import { day8input } from "../input/day8";

const day8Example1 = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

const day8Example2 = `....
..AA
..A.
....`;

const day8Example3 = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`;

describe("day 8", () => {
  test("day 8 part 1 example 1", () => {
    expect(day8part1(day8Example1)).toEqual(14);
  });

  test("day 8 part 1 example 2", () => {
    expect(day8part1(day8Example2)).toEqual(4);
  });

  test("day 8 part 1 real", () => {
    expect(day8part1(day8input)).toEqual(381);
  });

  test("day 8 part 2 example 1", () => {
    expect(day8part2(day8Example1)).toEqual(34);
  });

  test("day 8 part 2 example 3", () => {
    expect(day8part2(day8Example3)).toEqual(9);
  });

  test("day 8 part 2 real", () => {
    expect(day8part2(day8input)).toEqual(1184);
  });
});
